import { User } from '@/types';

const SHARED_OPERATIONAL_PASSWORD = 'Great2026!';

const REMOVED_USER_EMAILS = new Set([
  'gestor@great.com',
  'comercial@great.com',
  'feliperangel.rego03@gmail.com',
  'design@great.com',
  'coordenador@great.com',
  'editor@great.com',
  'atendente@great.com',
]);

const REQUESTED_OPERATIONAL_USERS: (User & { password: string })[] = [
  {
    id: 'operacional-isaque-soares',
    name: 'Isaque Soares',
    email: 'isaquegreatsd@gmail.com',
    password: SHARED_OPERATIONAL_PASSWORD,
    role: 'ATENDENTE',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'operacional-gustavo-lira',
    name: 'Gustavo Lira',
    email: 'gugaliraclash@gmail.com',
    password: SHARED_OPERATIONAL_PASSWORD,
    role: 'ATENDENTE',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'operacional-victoria-freitas',
    name: 'Victória Freitas',
    email: 'freitasviih00@gmail.com',
    password: SHARED_OPERATIONAL_PASSWORD,
    role: 'ATENDENTE',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'operacional-gerson-lopes',
    name: 'Gerson Lopes',
    email: 'gersonlopesgreat@gmail.com',
    password: SHARED_OPERATIONAL_PASSWORD,
    role: 'ATENDENTE',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'operacional-matheus-tchaka',
    name: 'Matheus Tchaka',
    email: 'ocdremex@gmail.com',
    password: SHARED_OPERATIONAL_PASSWORD,
    role: 'ATENDENTE',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'operacional-kauan-anderson',
    name: 'Kauan Anderson',
    email: 'kauananderson1919@gmail.com',
    password: SHARED_OPERATIONAL_PASSWORD,
    role: 'ATENDENTE',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'operacional-amanda-great',
    name: 'Amanda Great',
    email: 'amandagreatsd@gmail.com',
    password: SHARED_OPERATIONAL_PASSWORD,
    role: 'EDITOR_VIDEO',
    teamId: 'team-2',
    active: true,
    createdAt: new Date(),
  },
];

const INITIAL_USERS: (User & { password: string })[] = [
  {
    id: 'admin-1',
    name: 'Bruno Gomes',
    email: 'bruno@great.com',
    password: 'Brunogomes2005!',
    role: 'ADMIN',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'admin-pedro',
    name: 'Pedro Juan',
    email: 'pedroojuann1@gmail.com',
    password: 'Pedro2024!',
    role: 'ADMIN',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'cled-1',
    name: 'Cled',
    email: 'cled@great.com',
    password: 'Cled2001',
    role: 'COORDENADOR_COMERCIAL',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'hebert-1',
    name: 'Herbert',
    email: 'hebert@great.com',
    password: 'josehebert123',
    role: 'CLOSER',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'miguel-1',
    name: 'Miguel',
    email: 'miguel@great.com',
    password: 'Miguel24',
    role: 'SDR',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'felipe-1',
    name: 'Felipe',
    email: 'felipe@great.com',
    password: '343802',
    role: 'SDR',
    active: true,
    createdAt: new Date(),
  },
  {
    id: '1',
    name: 'Carlos Silva',
    email: 'comercial@great.com',
    password: 'demo123',
    role: 'SETOR_COMERCIAL',
    active: true,
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Ana Santos',
    email: 'gestor@great.com',
    password: 'demo123',
    role: 'GESTOR',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: '3',
    name: 'Pedro Costa',
    email: 'atendente@great.com',
    password: 'demo123',
    role: 'ATENDENTE',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: '4',
    name: 'Marcos Oliveira',
    email: 'coordenador@great.com',
    password: 'demo123',
    role: 'COORDENADOR_RED',
    active: true,
    createdAt: new Date(),
  },
  {
    id: '5',
    name: 'Julia Mendes',
    email: 'design@great.com',
    password: 'demo123',
    role: 'DESIGN',
    teamId: 'team-2',
    active: true,
    createdAt: new Date(),
  },
  {
    id: '6',
    name: 'Ricardo Alves',
    email: 'editor@great.com',
    password: 'demo123',
    role: 'EDITOR_VIDEO',
    teamId: 'team-2',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'test-user-1',
    name: 'Usuário Teste',
    email: 'user@teste.com',
    password: '123456',
    role: 'ATENDENTE',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'test-admin-1',
    name: 'Admin Teste',
    email: 'admin@teste.com',
    password: '123456',
    role: 'ADMIN',
    active: true,
    createdAt: new Date(),
  },
  ...REQUESTED_OPERATIONAL_USERS,
];

export function getAuthSeedUsers() {
  return INITIAL_USERS;
}

export function getRemovedAuthEmails() {
  return REMOVED_USER_EMAILS;
}

