-- Definitive My Day persistence and deletion fix for Supabase.
-- Goal:
-- 1) Keep My Day rows visible until the user manually removes them.
-- 2) Prevent deleted rows from being regenerated by sync triggers.
-- 3) Remove assigned tasks for every impacted user when the creator deletes the source task.
-- 4) Keep realtime and multi-tab clients in sync through the database.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Core schema hardening
-- ---------------------------------------------------------------------------

alter table if exists public.my_day_items
  alter column source_id type text
  using source_id::text;

alter table if exists public.my_day_items
  add column if not exists origin_reporter_user_id uuid references public.profiles(id) on delete set null;

alter table if exists public.my_day_items
  add column if not exists origin_reporter_name text;

alter table if exists public.my_day_items
  add column if not exists assigned_to_user_id uuid references public.profiles(id) on delete set null;

alter table if exists public.my_day_items
  add column if not exists assigned_by_user_id uuid references public.profiles(id) on delete set null;

create table if not exists public.my_day_item_exclusions (
  id uuid not null default gen_random_uuid() primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_date date not null,
  source text not null,
  source_id text not null default '',
  title text not null,
  created_by_user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create unique index if not exists my_day_item_exclusions_unique_key
  on public.my_day_item_exclusions (user_id, item_date, source, source_id, title);

create index if not exists idx_my_day_item_exclusions_user_lookup
  on public.my_day_item_exclusions (user_id, source, source_id, item_date);

create index if not exists idx_my_day_items_user_date
  on public.my_day_items (user_id, date);

create index if not exists idx_my_day_items_source_lookup
  on public.my_day_items (source, source_id);

create index if not exists idx_my_day_items_origin_reporter_user_id
  on public.my_day_items (origin_reporter_user_id);

create index if not exists idx_my_day_items_assigned_to_user_id
  on public.my_day_items (assigned_to_user_id);

create index if not exists idx_my_day_items_assigned_by_user_id
  on public.my_day_items (assigned_by_user_id);

create unique index if not exists my_day_items_unique_assignment
  on public.my_day_items (user_id, date, source, source_id, title);

-- Backfill assignment metadata for existing rows.
update public.my_day_items
set assigned_to_user_id = coalesce(assigned_to_user_id, user_id)
where assigned_to_user_id is null;

update public.my_day_items
set assigned_by_user_id = coalesce(assigned_by_user_id, origin_reporter_user_id)
where assigned_by_user_id is null;

update public.my_day_items
set origin_reporter_user_id = coalesce(origin_reporter_user_id, assigned_by_user_id)
where origin_reporter_user_id is null;

update public.my_day_items mdi
set origin_reporter_name = coalesce(
  nullif(mdi.origin_reporter_name, ''),
  p.full_name,
  p.email
)
from public.profiles p
where mdi.origin_reporter_user_id = p.id
  and coalesce(mdi.origin_reporter_name, '') = '';

-- Remove duplicated My Day rows before rebuilding the unique index.
delete from public.my_day_items a
using (
  select
    ctid,
    row_number() over (
      partition by user_id, date, source, source_id, title
      order by created_at, id
    ) as rn
  from public.my_day_items
) dup
where a.ctid = dup.ctid
  and dup.rn > 1;

-- ---------------------------------------------------------------------------
-- Helper functions
-- ---------------------------------------------------------------------------

create or replace function public.safe_uuid(p_value text)
returns uuid
language plpgsql
immutable
strict
as $$
begin
  return p_value::uuid;
exception
  when invalid_text_representation then
    return null;
end;
$$;

create or replace function public.sync_my_day_assignment_columns()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.user_id := coalesce(new.user_id, new.assigned_to_user_id);
  new.assigned_to_user_id := coalesce(new.assigned_to_user_id, new.user_id);
  new.origin_reporter_user_id := coalesce(new.origin_reporter_user_id, new.assigned_by_user_id);
  new.assigned_by_user_id := coalesce(new.assigned_by_user_id, new.origin_reporter_user_id);
  return new;
end;
$$;

create or replace function public.my_day_item_is_excluded(
  p_user_id uuid,
  p_item_date date,
  p_source text,
  p_source_id text,
  p_title text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.my_day_item_exclusions e
    where e.user_id = p_user_id
      and e.source = p_source
      and (
        (
          coalesce(nullif(trim(p_source_id), ''), '') <> ''
          and e.source_id = p_source_id
        )
        or (
          coalesce(nullif(trim(p_source_id), ''), '') = ''
          and e.item_date = coalesce(p_item_date, current_date)
          and lower(e.title) = lower(coalesce(p_title, ''))
        )
      )
  );
$$;

create or replace function public.persist_my_day_exclusion_on_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.my_day_item_exclusions (
    user_id,
    item_date,
    source,
    source_id,
    title,
    created_by_user_id,
    created_at
  )
  values (
    old.user_id,
    coalesce(old.date, current_date),
    coalesce(old.source, 'MANUAL'),
    coalesce(old.source_id, ''),
    coalesce(old.title, ''),
    coalesce(auth.uid(), old.assigned_by_user_id, old.origin_reporter_user_id),
    now()
  )
  on conflict (user_id, item_date, source, source_id, title)
  do update set
    created_by_user_id = coalesce(excluded.created_by_user_id, public.my_day_item_exclusions.created_by_user_id),
    created_at = now();

  return old;
end;
$$;

create or replace function public.handle_task_assignment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  reporter_name text;
  task_priority text;
  task_date date;
  assignee_ids uuid[];
  assignee_id uuid;
  source_id_text text;
begin
  if new.reporter_user_id is null then
    return new;
  end if;

  select coalesce(p.full_name, p.email)
    into reporter_name
  from public.profiles p
  where p.id = new.reporter_user_id;

  task_priority := coalesce(new.priority, 'MEDIA');
  task_date := coalesce(new.due_date, current_date);
  source_id_text := new.id::text;

  select array_agg(distinct candidate_id)
    into assignee_ids
  from (
    select public.safe_uuid(value) as candidate_id
    from jsonb_array_elements_text(coalesce(new.tags->'assignee_user_ids', '[]'::jsonb)) as t(value)

    union all

    select new.assignee_user_id
  ) assignees
  where candidate_id is not null;

  if coalesce(array_length(assignee_ids, 1), 0) = 0 then
    delete from public.my_day_items
    where source in ('WORK_ITEM', 'WORKITEM')
      and source_id = source_id_text;

    return new;
  end if;

  if tg_op = 'UPDATE' then
    delete from public.my_day_items
    where source in ('WORK_ITEM', 'WORKITEM')
      and source_id = source_id_text
      and not (user_id = any (assignee_ids));
  end if;

  foreach assignee_id in array assignee_ids loop
    if assignee_id is null then
      continue;
    end if;

    if public.my_day_item_is_excluded(assignee_id, task_date, 'WORK_ITEM', source_id_text, new.title) then
      continue;
    end if;

    insert into public.my_day_items (
      user_id,
      title,
      source,
      source_id,
      priority,
      status,
      date,
      deadline_date,
      deadline_time,
      deadline_notified,
      origin_reporter_user_id,
      origin_reporter_name,
      assigned_to_user_id,
      assigned_by_user_id
    )
    values (
      assignee_id,
      new.title,
      'WORK_ITEM',
      source_id_text,
      task_priority,
      'PENDENTE',
      task_date,
      task_date,
      null,
      false,
      new.reporter_user_id,
      reporter_name,
      assignee_id,
      new.reporter_user_id
    )
    on conflict (user_id, date, source, source_id, title)
    do update set
      title = excluded.title,
      priority = excluded.priority,
      status = excluded.status,
      deadline_date = excluded.deadline_date,
      deadline_time = excluded.deadline_time,
      deadline_notified = excluded.deadline_notified,
      origin_reporter_user_id = excluded.origin_reporter_user_id,
      origin_reporter_name = excluded.origin_reporter_name,
      assigned_to_user_id = excluded.assigned_to_user_id,
      assigned_by_user_id = excluded.assigned_by_user_id,
      updated_at = now();
  end loop;

  return new;
end;
$$;

create or replace function public.cleanup_on_work_item_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.my_day_items
  where source in ('WORK_ITEM', 'WORKITEM')
    and source_id = old.id::text;

  delete from public.notifications
  where related_entity = 'work_items'
    and related_entity_id::text = old.id::text;

  return old;
end;
$$;

-- ---------------------------------------------------------------------------
-- Trigger refresh
-- ---------------------------------------------------------------------------

drop trigger if exists sync_my_day_assignment_columns_trigger on public.my_day_items;
create trigger sync_my_day_assignment_columns_trigger
before insert or update on public.my_day_items
for each row
execute function public.sync_my_day_assignment_columns();

drop trigger if exists persist_my_day_exclusion_before_delete on public.my_day_items;
create trigger persist_my_day_exclusion_before_delete
before delete on public.my_day_items
for each row
execute function public.persist_my_day_exclusion_on_delete();

drop trigger if exists on_task_assigned on public.work_items;
create trigger on_task_assigned
after insert or update on public.work_items
for each row
execute function public.handle_task_assignment();

drop trigger if exists work_items_cleanup_after_delete on public.work_items;
create trigger work_items_cleanup_after_delete
after delete on public.work_items
for each row
execute function public.cleanup_on_work_item_delete();

-- ---------------------------------------------------------------------------
-- RLS policies
-- Keep compatibility with the current app while letting the database own
-- persistence and deletion behavior.
-- ---------------------------------------------------------------------------

alter table if exists public.work_items enable row level security;
alter table if exists public.my_day_items enable row level security;
alter table if exists public.my_day_item_exclusions enable row level security;

do $$
declare
  r record;
begin
  for r in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('work_items', 'my_day_items', 'my_day_item_exclusions')
  loop
    execute format('drop policy if exists %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;

create policy "work_items_select_public"
on public.work_items
for select
to public
using (true);

create policy "work_items_insert_public"
on public.work_items
for insert
to public
with check (true);

create policy "work_items_update_public"
on public.work_items
for update
to public
using (true)
with check (true);

create policy "work_items_delete_public"
on public.work_items
for delete
to public
using (true);

create policy "my_day_items_select_public"
on public.my_day_items
for select
to public
using (true);

create policy "my_day_items_insert_public"
on public.my_day_items
for insert
to public
with check (true);

create policy "my_day_items_update_public"
on public.my_day_items
for update
to public
using (true)
with check (true);

create policy "my_day_items_delete_public"
on public.my_day_items
for delete
to public
using (true);

create policy "my_day_item_exclusions_select_public"
on public.my_day_item_exclusions
for select
to public
using (true);

create policy "my_day_item_exclusions_insert_public"
on public.my_day_item_exclusions
for insert
to public
with check (true);

create policy "my_day_item_exclusions_update_public"
on public.my_day_item_exclusions
for update
to public
using (true)
with check (true);

create policy "my_day_item_exclusions_delete_public"
on public.my_day_item_exclusions
for delete
to public
using (true);

grant select, insert, update, delete on table public.work_items to anon, authenticated, service_role;
grant select, insert, update, delete on table public.my_day_items to anon, authenticated, service_role;
grant select, insert, update, delete on table public.my_day_item_exclusions to anon, authenticated, service_role;

do $$
begin
  alter publication supabase_realtime add table public.work_items;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.my_day_items;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.my_day_item_exclusions;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  perform pg_notify('pgrst', 'reload schema');
exception
  when undefined_function then null;
end $$;

commit;
