import { User } from '@/types';

const REMOVED_USER_EMAILS = new Set([
  'gestor@great.com',
  'comercial@great.com',
  'feliperangel.rego03@gmail.com',
  'design@great.com',
  'coordenador@great.com',
  'editor@great.com',
  'atendente@great.com',
  'bruno@great.com',
  'pedroojuann1@gmail.com',
  'cled@great.com',
  'hebert@great.com',
  'miguel@great.com',
  'felipe@great.com',
  'admin@teste.com',
  'freitasviih00@gmail.com',
]);

const INITIAL_USERS: (User & { password: string })[] = [
  {
    id: 'test-user-1',
    name: 'Usuario Teste',
    email: 'user@teste.com',
    password: '123456',
    role: 'ATENDENTE',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'seed-isaque',
    name: 'Isaque Soares',
    email: 'isaquegreatsd@gmail.com',
    password: 'Great2026!',
    role: 'ATENDENTE',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'seed-gustavo',
    name: 'Gustavo Lira',
    email: 'gugaliraclash@gmail.com',
    password: 'Great2026!',
    role: 'ATENDENTE',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'seed-gerson',
    name: 'Gerson Lopes',
    email: 'gersonlopesgreat@gmail.com',
    password: 'Great2026!',
    role: 'ATENDENTE',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'seed-tchaka',
    name: 'Matheus Tchaka',
    email: 'ocdremex@gmail.com',
    password: 'Great2026!',
    role: 'ATENDENTE',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'seed-kauan',
    name: 'Kauan Anderson',
    email: 'kauananderson1919@gmail.com',
    password: 'Great2026!',
    role: 'ATENDENTE',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'seed-amanda',
    name: 'Amanda Great',
    email: 'amanda.operacional@great.local',
    password: 'Great2026!',
    role: 'EDITOR_VIDEO',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'seed-brayton',
    name: 'Brayton Maycon',
    email: 'braytonmaycon5@gmail.com',
    password: 'Great2026!',
    role: 'GESTOR',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'seed-luiz',
    name: 'Jeferson Luiz',
    email: 'luiz46340@gmail.com',
    password: 'Great2026!',
    role: 'GESTOR',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'seed-carlos-andre',
    name: 'Carlos André',
    email: 'ci.andrade99@gmail.com',
    password: 'Great2026!',
    role: 'GESTOR',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'seed-cleriston',
    name: 'Cleriston Felipe',
    email: 'cleristonfelipe711@gmail.com',
    password: 'Great2026!',
    role: 'ATENDENTE',
    teamId: 'team-1',
    active: true,
    createdAt: new Date(),
  },
];

export function getAuthSeedUsers() {
  return INITIAL_USERS;
}

export function getRemovedAuthEmails() {
  return REMOVED_USER_EMAILS;
}

